// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk_1KD5qR0x65t45S5AjCY0jfVte88_bM',
    appId: '1:162620170289:web:b68ed13109c673f7c4f510',
    messagingSenderId: '162620170289',
    projectId: 'fir-flutter-codelab-de783',
    authDomain: 'fir-flutter-codelab-de783.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-de783.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM6Dqnj5yBZ_hs2tjZjll5a8YxScvVA4Q',
    appId: '1:162620170289:android:c5e6f45f804a5920c4f510',
    messagingSenderId: '162620170289',
    projectId: 'fir-flutter-codelab-de783',
    storageBucket: 'fir-flutter-codelab-de783.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRgCclOUfRdEwSk2_x744VCozA8_UfVAk',
    appId: '1:162620170289:ios:d17aca6aa135dc83c4f510',
    messagingSenderId: '162620170289',
    projectId: 'fir-flutter-codelab-de783',
    storageBucket: 'fir-flutter-codelab-de783.appspot.com',
    iosClientId: '162620170289-0cmudv314p676gbifn2nl5kh7mpmbaid.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRgCclOUfRdEwSk2_x744VCozA8_UfVAk',
    appId: '1:162620170289:ios:d17aca6aa135dc83c4f510',
    messagingSenderId: '162620170289',
    projectId: 'fir-flutter-codelab-de783',
    storageBucket: 'fir-flutter-codelab-de783.appspot.com',
    iosClientId: '162620170289-0cmudv314p676gbifn2nl5kh7mpmbaid.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
